services:
  bitwarden-test:
    build: .
    environment:
      BW_HOST: https://vault.bitwarden.com
      BW_CLIENTID: ${BW_CLIENTID}
      BW_CLIENTSECRET: ${BW_CLIENTSECRET}
      BW_PASSWORD: ${BW_PASSWORD}
    volumes:
      - ./data:/root/.config/Bitwarden CLI/
    env_file:
      - .env