---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bitwarden-secret-manager
rules:
  - apiGroups: [""]
    resources: ["secrets", "namespaces"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bitwarden-secret-manager-binding
subjects:
  - kind: ServiceAccount
    name: bitwarden-vault
    namespace: bitwarden-vault
roleRef:
  kind: ClusterRole
  name: bitwarden-secret-manager
  apiGroup: rbac.authorization.k8s.io
