apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-refresh-secrets
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: bitwarden-vault
      restartPolicy: OnFailure
      containers:
        - name: bitwarden-sync
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: bw-credentials
          volumeMounts:
            - name: bw-data
              mountPath: /root/.config/Bitwarden\ CLI/
      volumes:
        - name: bw-data
          persistentVolumeClaim:
            claimName: bitwarden-vault-pvc
