apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  labels:
    app.kubernetes.io/name: bitwarden-vault
    app.kubernetes.io/instance: {{ .Release.Name }}
