schedule: "0 * * * *"

image:
  repository: ghcr.io/murrou-cell/bitwarden-vault
  tag: main
  pullPolicy: Always

# Persistent storage for Bitwarden CLI data.json
persistence:
  size: 1Gi
  storageClass: "" # optional, leave empty for default
